
source 'https://github.com/cocoapods/specs.git'

use_frameworks!

platform :ios, '8.0'

target 'YHDynamicButton_Example' do
  pod 'YHDynamicButton', :path => '../'

  target 'YHDynamicButton_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
  end
end
